dash/urls.py
from django.urls import path
from . import views

app_name = 'dash'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.user_login, name='login'),
    path('adminPage/', views.adminPage, name='adminPage'),
    path('logout/', views.user_logout, name='logout')

]

metric/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include


urlpatterns = [
    path('dash/', include('dash.urls')),
    path('admin/', admin.site.urls),
]

dash/models.py
from django.db import models
from .create import CustomUserManager
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.utils import timezone
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.contrib.auth.base_user import BaseUserManager


class CustomUserManager(BaseUserManager):
#Custom user model manager where email is the unique identifiersfor authentication instead of usernames.

    def create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError(_('The Email must be set'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user 

class CustomUser(AbstractBaseUser, PermissionsMixin):
    #user = models.OneToOneField(User,on_delete=models.CASCADE)
    username = None
    email = models.EmailField(('email address'), unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()
    
    def __str__(self):
        return self.email

dash/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from django import forms
from .models import CustomUser
from django.core import mail
from django.contrib.auth.models import User
from django.utils import timezone


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('email',)

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email',)

class adminLoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = CustomUser
        field =('email', 'password', )

class updateForm(forms.Form):
    tittle = forms.TextInput()
    story = forms.Textarea()
    time_posted = timezone.now()
    post_no = forms.IntegerField()
    class Meta:
        model = CustomUser
        field = ('tittle', 'story', 'time_posted')

dash/views.py
from django.shortcuts import render, redirect
from django.views import View
from dash.forms import adminLoginForm, updateForm
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout 
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
#import logging #to do some dubugging
#logger = logging.getLogger(__name__) #also for debbuging

# Create your views here.

    
def index(request):
    return render(request, 'dash/index.html' )

@login_required
def adminPage(request):
    return render(request, 'dash/adminPage.html',)

def user_login(request):
    
    form = adminLoginForm(request.POST)
    if request.method == "POST":
        email = request.POST.get('email')
        password = request.POST.get('password')
        #logger.error('Email: ')
        #logger.error(email)
        #logger.error('Password: ')
        #logger.error(password)
        #logger.error('Request: ')
        #logger.error(request.POST)

        user= authenticate(email=email, password=password) #fetch emial and password correspond from db
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('dash:adminPage'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'dash/login.html', {'form': form})

def user_logout(request):
    logout(request)
    return redirect('dash:index')

def new_post(request):  
    if request.method == "POST":
        form = updateForm(request.POST)
        if form.is_valid():
            form.save
            return redirect('dash:index')
    else:
        form = updateForm
    return render(request, 'dash/adminPage.html',  {'form': form})

dash/templates/dash/adminPage.html
{% extends "dash/frame.html" %}
{% block content %}
    {% block body_block %}
        {% csrf_token %}
    {% endblock %}

    {% load static %}

    {% block title %}
        <h1>welcome to Adminpage:</h1>
    {% endblock %}

    {% block body %}
        <form method='POST' class="post-form">
            {%csrf_token%}
            {{form.as_p}}
            <input type ='submit' value='Post' class="btn btn-primary">
        </form>
    {% endblock %}

    {% block footer %}
       <h3> <a href="{% url 'dash:logout' %}">{{ logout }}logout</a></h3>
    {% endblock %}
{% endblock %}

dash/templates/dash/frame.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Metric</title>
    <header>Metric</header>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>

    <body class ="container">
      {% block content %}
      {% endblock %}
    </body>
    <footer class="blog-footer">
        <h3><a href=>About Us</a></h3>
    </footer>
</html>

dash/templates/dash/index.html
{% extends "dash/frame.html" %}
{% block content %}

  {% load static %}
 
  {% block body_block %}
    {% csrf_token %}
  {% endblock %}

    <h1>Welcome to the Metric !</h1>
    <h4>
      <a href='{% url "dash:login" %}'> login as admin</a>
    </h4>
    
{% endblock %}

dash/templates/dash/login.html
{% extends "dash/frame.html" %}
{% block content %}

    {% load static %}

    {% block title %}
        <h1>Admin Login:</h1>
    {% endblock %}
       
    {% block login %}
        <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" name="" value="login" class="btn btn-primary">
        </form>
        <h2><a href="{% url 'dash:index' %}" class="btn btn-primary">{{ Home }}Home</a></h2>
    {% endblock %}
{% endblock %}

dash/templates/dash/static.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Metric</title>
    <header>Metric</header>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>

    <body class ="container">
      {% block content %}
      {% endblock %}
    </body>
    <footer class="blog-footer">
        <h3><a href=>About Us</a></h3>
    </footer>
</html>